apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: ola-v2
  labels:
    app: ola
    version: v2
    demo: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ola
  template:
    metadata:
      labels:
        app: ola
        version: v2
    spec:
      containers:
      - name: ola
        image: rafabene/ms4demo:node
        env:
        - name: VERSION
          value: "V2"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
        ports:
        - containerPort: 8080