apiVersion: apps/v1
kind: Deployment
metadata:
  name: ola-v2
  namespace: microservices
  labels:
    app: ola
    version: v2
    demo: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ola
      version: v2
  template:
    metadata:
      labels:
        app: ola
        version: v2
    spec:
      containers:
      - name: ola
        image: rafabene/ms4demo:node
        env:
        - name: VERSION
          value: "V2"
        - name: DEBUG
          value: "express-mysql-session*"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http-3000
          protocol: TCP