apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: ola-v1
  labels:
    app: ola
    version: v1
    demo: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ola
      version: v1
  template:
    metadata:
      labels:
        app: ola
        version: v1
    spec:
      containers:
      - name: ola
        image: rafabene/ms4demo:node
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP