apiVersion: apps/v1
kind: Deployment
metadata:
  name: ola-v1
  namespace: microservices
  labels:
    app: ola
    version: v1
    demo: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ola
      version: v1
  template:
    metadata:
      labels:
        app: ola
        version: v1
    spec:
      containers:
      - name: ola
        image: rafabene/ms4demo:node
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: "V1"
        - name: DEBUG
          value: "express-mysql-session*"
        ports:
        - containerPort: 3000
          name: http-3000
          protocol: TCP