kind: Service
apiVersion: v1
metadata:
  name: ola
  namespace: microservices
  labels:
    app: ola
    demo: cicd
spec:
  selector:
    app: ola
  type: NodePort
  ports:
  - protocol: TCP
    name: http-3000
    port: 3000
    targetPort: 3000